name: Build production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install ruby mruby libmruby-dev
          url='https://raw.githubusercontent.com/simple2d/simple2d/master/bin/simple2d.sh'; which curl > /dev/null && cmd='curl -fsSL' || cmd='wget -qO -'; bash <($cmd $url) install -y
          sudo gem install ruby2d
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build executable
        run: |
          sudo ruby2d build --native ${{ github.workspace }}/main.rb
          sudo ruby2d build --web ${{ github.workspace }}/main.rb
          sudo ruby2d build --macos ${{ github.workspace }}/main.rb
      - name: Upload build directory
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}/build