name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: apt update
      run: sudo apt update
    - name: apt install mruby libmruby-dev
      run: sudo apt install mruby libmruby-dev
    - name: simple2h.sh install
      run: url='https://raw.githubusercontent.com/simple2d/simple2d/master/bin/simple2d.sh'; which curl > /dev/null && cmd='curl -fsSL' || cmd='wget -qO -'; bash <($cmd $url) install -y
    - name: Build executable
      run: ruby2d build Main.rb