name: MacOS VM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: macos-latest

    steps:
      - name: Setup environment
        run: brew install mruby && brew tap simple2d/tap && brew install simple2d && gem install ruby2d
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build executable
        run: ruby2d build --all ${{ github.workspace }}/Main.rb